config/routes.rb
Rails.application.routes.draw do
  get 'users/premium_to_standard'

  resources :wikis do
    resources :collaborators
  end
  resources :charges, only: [:new, :create]
  resources :users, only: [] do
    post 'premium_to_standard' => 'users#premium_to_standard', as: :premium_to_standard
  end
  
  root 'welcome#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/collaborator.rb
class Collaborator < ApplicationRecord
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:standard, :premium, :admin]

  before_save { self.email = email.downcase if email.present? }
  before_save { self.role ||= :standard }

  after_update :downgrade_wikis, if: :standard?

  has_many :wikis, dependent: :destroy
  has_many :collaborators

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :confirmable, :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable

  def downgrade_wikis
    self.wikis.update_all(private: false)
  end

end

app/models/wiki.rb
class Wiki < ApplicationRecord
  belongs_to :user
  has_many :collaborators, dependent: :destroy
  has_many :users, through: :collaborators

  validates :title, length: {minimum: 5}, presence: true
  validates :body, length: {minimum: 10}, presence: true
  validates :user, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include Pundit
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @stripe_btn_data = {
        :key => Rails.configuration.stripe[:publishable_key].to_s,
        :description => "Blocipedia Premium - #{current_user.email}",
        :amount => 1500
    }
  end

  def create
    @amount = 1500

    customer = Stripe::Customer.create(
      :email => current_user.email,
      :source => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer => customer.id,
      :amount => @amount,
      :description => "Blocipedia Premium - #{current_user.email}",
      :currency => 'usd'
    )

    current_user.update_attribute(:role, 'premium')
    redirect_to root_path(current_user)
    flash[:notice] = "Your account, #{current_user.email} has been updated to Premium."

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to new_charge_path
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  def new
    @wiki = authorize Wiki.find(params[:wiki_id])
    @collaborator = Collaborator.new
  end

  def create
    @wiki = authorize Wiki.find(params[:wiki_id])
    @collaborator = Collaborator.new
    @collaborator.user_id = params[:collaborator][:user_id]
    @collaborator.wiki_id = @wiki.id

    if @collaborator.save
      flash[:notice] = "Collaborator was added."
      redirect_to new_wiki_collaborator_path
    else
      flash.now[:alert] = "There was an error adding the collaborator. Please try again."
      render :new
    end
  end

  def destroy
    @wiki = authorize Wiki.find(params[:wiki_id])
    @collaborator = Collaborator.find(params[:id])
    user = @collaborator.user_id
    @collaborator = Collaborator.where(user_id: user, wiki_id: @wiki.id)

    if Collaborator.destroy(@collaborator.ids)
      flash[:notice] = "Collaborator was successfully deleted."
      redirect_to new_wiki_collaborator_path
    else
      flash.now[:alert] = "There was an error deleting the collaborator."
      render :show
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def premium_to_standard
    current_user.update_attributes(role: 'standard')

    flash[:notice] = "Your account, #{current_user.email} has been downgraded to Standard."
    redirect_to new_charge_path
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = authorize Wiki.find(params[:id])
  end

  def new
    @wiki = authorize Wiki.new
  end

  def create
    @wiki = authorize Wiki.new(wiki_params)
    @wiki.user = current_user

    if @wiki.save
      flash[:notice] = "Wiki was saved!"
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = authorize Wiki.find(params[:id])
  end

  def update
    @wiki = authorize Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)

    if @wiki.save
      flash[:notice] = "Wiki was updated."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving the wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = authorize Wiki.find(params[:id])

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to action: :index
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end

  private
    def wiki_params
      params.require(:wiki).permit(:title, :body, :private)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    Redcarpet::Markdown.new(Redcarpet::Render::HTML).render(text).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
  def user_is_authorized_for_private?
    current_user.premium? || current_user.admin?
  end

  def user_is_authorized_for_edit?
    current_user
  end

  def user_is_authorized_for_delete?
    current_user && current_user.admin?
  end

  def user_is_authorized_for_collaborator_edit?
    @wiki.user || current_user.premium?
  end

  def wiki_has_collaborators?
    @wiki.collaborators.any?
  end

  def find_users()
    users = []
    collaborators = Collaborator.pluck(:user_id) # find all user_id's that are currently collaborators
    all_users = User.all
    all_users.each do |user|
      if !collaborators.include?(user.id)
        users << user # if user is not a collaborator, add to list
      end
    end
    users
    puts users
  end
end

app/views/charges/new.html.erb
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">Pricing</h1>
  <p class="lead">Ready to create private Wikis? Upgrade today!</p>
</div>

<div class="card-deck">
  <div class="card mb-4 shadow-sm">
    <div class="card-header">
      <h4 class="my-0 font-weight-normal">Standard</h4>
    </div>
    <div class="card-body">
      <h1 class="card-title pricing-card-title">Free
      </h1>
      <ul class="list-unstyled mt-3 mb-4">
        <li>Unlimited Public Wikis</li>
      </ul>
      <% if current_user.role == 'standard' %>
        <a href="#" class="btn btn-lg btn-block btn-primary disabled">Current Plan</a>
      <% else %>
        <%= link_to "Downgrade Plan", user_premium_to_standard_path(current_user), data: { confirm: 'Your private Wikis will become public. Are you sure you want to downgrade?' }, method: :post, :class => 'btn btn-lg btn-block btn-primary' %>
      <% end %>
    </div>
  </div>
  <div class="card mb-4 shadow-sm">
    <div class="card-header">
      <h4 class="my-0 font-weight-normal">Premium</h4>
    </div>
    <div class="card-body">
      <h1 class="card-title pricing-card-title">$15
      </h1>
      <ul class="list-unstyled mt-3 mb-4">
        <li>Unlimited Public & Private Wikis</li>
      </ul>
      <% if flash[:error].present? %>
        <div id="error_explanation">
        <p><%= flash[:error] %></p>
        </div>
      <% end %>
      <% if current_user.role == 'standard' %>
        <%= form_tag charges_path do %>
          <script src="https://checkout.stripe.com/checkout.js" data-label="Upgrade" class="stripe-button" data-key="<%= Rails.configuration.stripe[:publishable_key] %>" data-description="Blocipedia Premium Upgrade" data-amount="1500" data-locale="auto"></script>
      <% end %>
      <% else %>
        <a href="#" class="btn btn-lg btn-block btn-primary disabled">Current Plan</a>
      <% end %>
    </div>
  </div>
</div>

app/views/collaborators/_collaborator.html.erb
<div class="row">
  <div class="col-md-8">
    <%= form_for [@wiki, Collaborator.new] do |f| %>
      <% if policy(@wiki).private? %>
        <div class="form-group">
          <%= f.label "Add Collaborator" %><br>
          <%= f.select :user_id, options_from_collection_for_select(User.where.not(id: @wiki.users), :id, :email), class: 'form-control' %>
        </div>
          <div class="form-group">
          <%= f.submit "Add", class: 'btn btn-info' %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>


<ul class="list-group">
  <% @wiki.collaborators.each do |f| %>
     <% user = User.find(f.user_id) %>
       <li class="list-group-item">
       <%= link_to "X", wiki_collaborator_path(@wiki, f), class: 'btn btn-danger btn-sm', method: :delete %>
       <%=user.email %>
       </li>
  <% end %>
</ul>

app/views/collaborators/new.html.erb
<%= render partial: "collaborator" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocipedia</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </head>

  <body>
  <div class='d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm'>
    <h5 class='my-0 mr-md-auto font-weight-normal'><%= link_to 'Blocipedia', root_path, :class => 'my-0 mr-md-auto font-weight-normal' %></h5>
    <nav class='my-2 my-md-0 mr-md-3'>
      <% if user_signed_in? %>
        <strong><%= current_user.email %></strong>
        <%= link_to 'Wikis', wikis_path, :class => 'p-2 text-dark' %>
        <%= link_to 'Profile', edit_user_registration_path, :class => 'p-2 text-dark' %>
      </nav>
      <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, :class => 'btn btn-outline-primary' %>
    <% else %>
      <%= link_to 'Wikis', wikis_path, :class => 'p-2 text-dark' %>
    </nav>
    <%= link_to 'Sign In', new_user_session_path, :class => 'btn btn-outline-primary' %>
  <% end %>

  </div>
  <div class="container">
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </div>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <center>
    <h1>Blocipedia: Social, Markdown Wikis</h1>
    <p>Create and share Markdown Wikis</p>
    <p>
      <% if user_signed_in? %>
        <%= link_to "Create New Wiki", new_wiki_path, :class => 'btn btn-primary' %>
      <% else %>
        <%= link_to "Sign Up", new_user_registration_path, :class => 'btn btn-primary' %>
      <% end %>
    </p>
  </center>
</div>

<center>
  <div class="row">
    <div class="col-md-6">
      <h2>Free Plan</h2>
      <p>Create as many public wikis as you want</p>
    </div>
    <div class="col-md-6">
      <h2>Premium Plan</h2>
      <p>Create private wikis!</p>
    </div>
  </div>
</center>

app/views/wikis/_form.html.erb
<div class="row">
  <div class="col-md-4">
    <p>Guidelines for wikis:</p>
    <ul>
      <li>Make sure the wiki is appropriate.</li>
      <li>Never insult dogs.</li>
      <li>Smile when you type.</li>
    </ul>
  </div>
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group" style="margin-bottom: 0px">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      </div>
      <div class="row" style="margin-bottom: 16px">
        <div class="col-auto">
          <small><strong><a href ="https://guides.github.com/features/mastering-markdown">Use Markdown</a></strong></small>
        </div>
        <div class="col-auto">
          <small>**bold**</small>
        </div>
        <div class="col-auto">
          <small>_italic_</small>
        </div>
        <div class="col-auto">
          <small>`code`</small>
        </div>
        <div class="col-auto">
          <small>>quote</small>
        </div>
        <div class="col-auto">
          <small>* or - bullet list</small>
        </div>
      </div>
      <% if current_user.admin? || current_user.premium? %>
        <div class="form-group">
          <%= f.label :private, class: 'checkbox' do %>
            <%= f.check_box :private %> Private wiki
          <% end %>
        </div>
      <% end %>
  <div class="form-group">
      <%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<%= render partial: 'form', locals: { wiki: @wiki } %>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>

<div class="row">
  <div class="col-md-8">
    <% @wikis.each do |wiki| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to wiki.title, wiki_path(wiki.id) %>
          </h4>
          <small>
            <%= markdown(wiki.body) %>
          </small>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-4">
    <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' if policy(Wiki).new? %>
  </div>
</div>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<%= render partial: 'form', locals: { wiki: @wiki } %>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>
  <%= link_to "Edit Wiki", edit_wiki_path, class: 'btn btn-success' if policy(@wiki).edit? %>

  <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } if policy(@wiki).destroy? %>

  <%= link_to "Edit Collaborators", new_wiki_collaborator_path(@wiki), class: 'btn btn-info' if policy(@wiki).private? %>

<p><%= markdown(@wiki.body) %></p>